@startuml

entity Customer {
    *customer_id : integer <<generated>>
    --
    **dni** : varchar(10) <<unique>>
    nombre : varchar(9)
    **email** : varchar(7) <<unique>>
    fecha_registro : date
}



entity "Direccion" as Address {
    *address_id : integer
    --
    *customer_id : Customer <<FK>>
    calle : varchar(6)
    ciudad : varchar(5)
    codigo_postal : varchar(4)
    principal : boolean
}


entity "Orden" as Orderp {
    * **orderp_id** : integer <<generated>>
    --
    *customer_id : Customer <<FK>>
    *shipping_address_id : Address <<FK>>
    fecha : datetime
    estado : varchar(10)
    total : float
}



@enduml